@startuml

class 店員
class 店舗

class 販売 {
  年月日時刻
  /販売総額
  値引き額
}

class 販売明細 {
  数雨量
  実販売価格
}

class 商品
class 商品価格

店員 "販売者 0..1"--"*" 販売
店員 "登録者 1"---"*" 販売
店舗 "1"--"*" 販売
販売 "1"--"1..*" 販売明細
販売明細 "*"-r-"1" 商品
商品 "時点 1"--"1" 商品価格

@enduml
