@startuml

class 刑罰法規
class 犯罪構成要件
class 行為
class 違法行為
class 非違法行為
class 違法性阻却事由

刑罰法規 "1"-r-"*" 犯罪構成要件 : 規定する
犯罪構成要件 "1..*"--"*" 行為 : 該当する
違法行為 -u-|> 行為
非違法行為 -u-|> 行為
非違法行為 "*"--"1" 違法性阻却事由

@enduml
