@startuml

class 社員 {
  社員番号
  氏名
}

class 日別作業実績 {
  年月日
  /合計作業時間
}

class 日別作業実績明細 {
  作業時間
}

class プロジェクト {
  プロジェクト名称
}

社員 "1"-r-"*" 日別作業実績
日別作業実績 "1"--"1..*" 日別作業実績明細
日別作業実績明細 "*"-r-"1" プロジェクト


@enduml
