@startuml

class 顧客 {
  顧客番号
  氏名
  住所
  電話番号
}

class 注文 {
  年月日時刻
  売買区分
  数量
}

class 指値注文 {
  金額
}

class 成行注文

class 銘柄 {
  銘柄コード
  名称
}

注文 <|-- 指値注文
注文 <|-- 成行注文

顧客 "1"-r-"*" 注文
注文 "*"-r-"1" 銘柄

@enduml
