@startuml

class 顧客

class 性別区分 {
  名称
}

class 年齢区分 {
  名称
}

class 売上 {
  年月日時刻
  /売上額
}

class 売上明細 {
  数量
}

class 商品 {
  名称
  価格
}

顧客 "*"--"1" 性別区分
顧客 "*"--"1" 年齢区分
顧客 "1"-r-"*" 売上
売上 "1"--"*" 売上明細
売上明細 "*"-r-"1" 商品

@enduml
