@startuml

class 年齢層 {
  年齢層区分
}

class 性年齢層 {
  性年齢層区分
}

class 店舗 {
  名称
}

class 売上 {
  計上日
  /金額
}

class 売上明細 {
  数量
}

class 商品 {
  名称
  金額
}

年齢層 "1"--"*" 性年齢層
性年齢層 "1"-r-"*" 売上
店舗 "1"--"*" 売上
売上 "1"--"1..*" 売上明細
売上明細 "*"-r-"1" 商品

@enduml
