@startuml

class 顧客 {
  名称
  住所
  電話番号
}

class 請求方法 {
}

class 銀行口座引き落とし請求 {
  銀行コード
  視点コード
  口座種別
  口座番号
  名義人氏名
}

class カード引き引き落とし請求 {
  カード番号
  有効期限
  名義人氏名
}

class 請求書請求 {
  請求先住所
  請求先氏名
}

顧客 "1"-ri-"1" 請求方法
請求方法 <|-- 銀行口座引き落とし請求
請求方法 <|-- カード引き引き落とし請求
請求方法 <|-- 請求書請求

@enduml
