@startuml

class 会員顧客 {
  名称
  住所
  メールアドレス
  パスワード
}

class 受注 {
  年月日時刻
  /金額
}

class 受注明細 {
  数量
}

class 商品 {
  商品名
  販売価格
}

会員顧客 "1"-right-"*" 受注
受注 "1"--"1..*" 受注明細
受注明細 "*"-right-"1" 商品

@enduml
