@startuml

class 営業員 {
  社員番号
  氏名
}

class 顧客 {
  氏名
  住所
}

class 販売 {
  年月日時刻
  /販売価格
  割引き額
  納車予定日
}

class 中古車 {
  車種
  年式
  走行距離
  価格
}

営業員 "1"--"*" 販売
顧客 "1"--"*" 販売
中古車 "1"--"0..1" 販売

@enduml
