@startuml

class 電話帳登録者 {
  氏名
}

class 登録電話番号 {
  電話番号
}

class 着信 {
  年月日時刻
  電話番号通知区分
  電話番号
}

class 発信 {
  年月日時刻
  電話番号通知区分
  電話番号
}

電話帳登録者 "1"-d-"*" 登録電話番号
登録電話番号 "0..1"--"*" 着信
登録電話番号 "0..1"--"*" 発信

@enduml
