@startuml

entity 会員顧客 {
  + 顧客ID
}

entity 受注 {
  + 受注ID
  ---
  年月日時刻
  金額
  # 顧客ID
}

entity 受注明細 {
  + 受注ID (FK)
  + 明細行
  ---
  数量
  # 商品ID
}

entity 出荷 {
  + 出荷ID
  ---
  年月日時刻
  金額
  # 受注ID
}

entity 出荷明細 {
  + 出荷ID (FK)
  + 明細行
  ---
  数量
  # 商品ID
}

entity 商品 {
  + 商品ID
  ---
  商品名
  販売価格
}

会員顧客 ||-r-o{ 受注
受注 ||--|{ 受注明細
受注 ||-r-o{ 出荷
出荷 ||--|{ 出荷明細
受注明細 }o--|| 商品
出荷明細 }o--|| 商品

@enduml
