@startuml

entity 商品 {
  + 商品ID
  ---
  名称
  価格
}

entity セット商品 {
  + 商品ID (FK)
}

entity 単体商品 {
  + 商品ID (FK)
}

entity セット商品構成 {
  + セット商品ID (FK)
  + 単体商品ID (FK)
}

商品 ||--o{ セット商品
商品 ||--o{ 単体商品
セット商品 ||--|{ セット商品構成
単体商品 ||--o{ セット商品構成

@enduml
