@startuml

class 名寄せ会員 {
  名称
}

class 会員 {
  会員ID
  名称
}

class オークション会員 {
}

class メール会員 {
}

class ブログ会員 {
}

名寄せ会員 "1"--"1..*" 会員
会員 "1"--"0..1" オークション会員
会員 "1"--"0..1" メール会員
会員 "1"--"0..1" ブログ会員

@enduml
