@startuml

entity 会員顧客 {
  + 会員ID
  ---
  名称
  住所
  メールアドレス
  パスワード
}

entity 受注 {
  + 受注番号
  ---
  年月日時刻
  金額
  # 会員ID (FK)
}

entity 受注明細 {
  + 受注番号 (FK)
  + 受注明細行番号
  ---
  数量
  # 商品コード (FK)
}

entity 商品 {
  + 商品コード
  ---
  商品名
  販売価格
}

会員顧客 ||.r.o{ 受注
受注 ||--|{ 受注明細
受注明細 }o.r.|| 商品

@enduml
