@startuml

class メーカー

class 商品種別 {
  名称
}

class 商品 {
  商品コード
  商品名
  メーカー型番
}

class 商品属性種別 {
  名称
  単位
}

class 商品属性 {
  値
}

メーカー "1"--r--"*" 商品

商品種別 "1"-d-"*" 商品
商品属性種別 "1"-d-"*" 商品属性

商品種別 "1"-r-"*" 商品属性種別
商品 "1"--r--"*" 商品属性

@enduml
