@startuml

class 単語
class 品詞
class 自立語
class 付属語
class 活用自立語
class 非活用自立語
class 動詞
class 形容詞
class 形容動詞
class 名詞
class 代名詞
class 連体詞
class 副詞
class 接続詞
class 感動詞
class 助動詞
class 助詞


単語 "*"-r-"1" 品詞
自立語 -u-|> 単語
付属語 -u-|> 単語
活用自立語 -u-|> 自立語
非活用自立語 -u-|> 自立語
動詞 -u-|> 活用自立語
形容詞 -u-|> 活用自立語
形容動詞 -u-|> 活用自立語
名詞 -u-|> 非活用自立語
代名詞 -u-|> 非活用自立語
連体詞 -u-|> 非活用自立語
副詞 -u-|> 非活用自立語
接続詞 -u-|> 非活用自立語
感動詞 -u-|> 非活用自立語
助動詞 -u-|> 付属語
助詞 -u-|> 付属語

@enduml
