@startuml

class 品詞
class 自立語
class 付属語
class 活用を持つ自立語
class 活用を持たない自立語
class 活用を持つ付属語
class 活用を持たない付属語

自立語 -u-|> 品詞
付属語 -u-|> 品詞
活用を持つ自立語 -u-|> 自立語
活用を持たない自立語 -u-|> 自立語
活用を持つ付属語 -u-|> 付属語
活用を持たない付属語 -u-|> 付属語

@enduml
