@startuml

class 結論
class 論証
class 単体論証
class 合流論証
class 単純論証
class 結合論証
class 根拠

論証 "*"-r-"1" 結論
単体論証 -u-|> 論証
合流論証 -u-|> 論証
単体論証 "2..*"--"*" 合流論証
単純論証 -u-|> 単体論証
結合論証 -u-|> 単体論証
根拠 "1"--"*" 単純論証 : < 提示する
根拠 "2..*"--"*" 結合論証 : < 提示する

@enduml
