@startuml

class 刑罰法規
class 犯罪構成要件
class 行為
class 違法行為
class 非違法行為
class 違法性阻却事由
class 行為者
class 責任無能力者区分
class 責任無能力者
class 限定責任能力者
class 責任能力者

刑罰法規 "1"-r-"*" 犯罪構成要件 : 規定する
犯罪構成要件 "1..*"--"*" 行為 : 該当する
違法行為 -l-|> 行為
非違法行為 -l-|> 行為
非違法行為 "*"--"1" 違法性阻却事由
行為 "1"--"1..*" 行為者
責任無能力者区分 "0..1"--"*" 行為者
責任無能力者 --|> 行為者
限定責任能力者 --|> 行為者
責任能力者 --|> 行為者

@enduml
