@startuml

class Customer {
  name
  address
  email
}

class IndividualCustomer {
  sex
  birthday
}

class CoporateCustomer {
  capital_stock
}

Customer <|-- IndividualCustomer
Customer <|-- CoporateCustomer

@enduml
