@startuml

class 会員 {
  会員ID
  ニックネーム
  パスワード
}

class オークション会員 {
  連絡先住所
  連絡先氏名
  銀行口座番号
}

class ブログ会員 {
  日記タイトル
  連絡先メールアドレス
}

class Webメール会員 {
  メールアドレス
}

会員 "1"--"0..1" オークション会員
会員 "1"--"0..1" ブログ会員
会員 "1"--"0..1" Webメール会員

@enduml
