@startuml

class 社員
class 顧客企業

class 営業担当 {
  開始年月日
  終了年月日
}

社員 "1"--"*" 営業担当
note on link : ある時点において、1人の社員は複数の顧客企業の営業担当になることができる

顧客企業 "1"--"0..1" 営業担当
note on link : ある時点において、顧客企業の営業担当の社員はせいぜい1人である

@enduml
