@startuml

class 社員 {
  社員番号
  氏名
}

class 経費申請 {
  申請年月日時刻
  経費発生日
  金額
  申請内容説明
  /承認ステータス
}

class 経費申請確認 {
  確認年月日時刻
  承認/却下区分
  却下理由
}

社員 "1"--"*" 経費申請 : 申請者
社員 "1"--"*" 経費申請確認 : 確認者
経費申請 "1"--"0..1" 経費申請確認

@enduml
