@startuml

class 地域区分 {
  名称
}

class 重量区分 {
}

class 配送料金 {
  金額
}
note right : <<制約>>\n配送料金は、重量区分、配送元、配送先の\n組み合わせに対して設定する

地域区分 "1"---"*" 配送料金 : 配送先
地域区分 "1"---"*" 配送料金 : 配送元
重量区分 "1"-l-"*" 配送料金

@enduml
