@startuml

[*] --> 出荷準備完了 : [在庫あり]/在庫引当

[*] --> 入荷待ち : [在庫切れ]/発注
入荷待ち --> 出荷準備完了 : 入荷/在庫引当

出荷準備完了 --> 出荷済み : [代金の請求に成功]/出荷
出荷準備完了 --> 出荷停止 : [代金の請求に失敗]/メール連絡

出荷済み --> 入金済み : 入金

入金済み --> [*]
出荷停止 --> [*]

@enduml
