@startuml

class ノード {
  名称
}

class ディレクトリ
class ファイル
class 一般ファイル
note left: ショートカット以外のファイル
class ショートカット

ノード <|-- ディレクトリ
ノード <|-- ファイル
ファイル <|-- 一般ファイル
ファイル <|-- ショートカット

ノード "*"--"0..1" ディレクトリ : ディレクトリとファイルはツリー構造
ショートカット "*"--"1" ノード : ショートカットに対する\nショートカットは作成できない

@enduml
